name: demoGit_env
channels:
- defaults
- conda-forge
- anaconda
- spedas
dependencies:
- python==3.11.5
- numpy==1.26.2
- requests==2.31.0
- cdflib=0.4.9
- cdasws==1.7.43
- netCDF4==1.6.2
- ipython==8.15.0
- pip==23.3.1
- pip:
  - pytplot-mpl-temp>=2.2.1
  - pyspedas==1.5.13